from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Game(object):
    def setupUi_game(self, Form):
        Form.setObjectName("Form")
        Form.resize(474, 502)
        self.pbn_1 = QtWidgets.QPushButton(Form)
        self.pbn_1.setGeometry(QtCore.QRect(40, 80, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_1.setFont(font)
        self.pbn_1.setText("")
        self.pbn_1.setDefault(False)
        self.pbn_1.setFlat(False)
        self.pbn_1.setObjectName("pbn_1")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pbn_1)
        self.pbn_2 = QtWidgets.QPushButton(Form)
        self.pbn_2.setGeometry(QtCore.QRect(120, 80, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_2.setFont(font)
        self.pbn_2.setText("")
        self.pbn_2.setDefault(False)
        self.pbn_2.setFlat(False)
        self.pbn_2.setObjectName("pbn_2")
        self.buttonGroup.addButton(self.pbn_2)
        self.pbn_3 = QtWidgets.QPushButton(Form)
        self.pbn_3.setGeometry(QtCore.QRect(200, 80, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_3.setFont(font)
        self.pbn_3.setText("")
        self.pbn_3.setDefault(False)
        self.pbn_3.setFlat(False)
        self.pbn_3.setObjectName("pbn_3")
        self.buttonGroup.addButton(self.pbn_3)
        self.pbn_4 = QtWidgets.QPushButton(Form)
        self.pbn_4.setGeometry(QtCore.QRect(280, 80, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_4.setFont(font)
        self.pbn_4.setText("")
        self.pbn_4.setDefault(False)
        self.pbn_4.setFlat(False)
        self.pbn_4.setObjectName("pbn_4")
        self.buttonGroup.addButton(self.pbn_4)
        self.pbn_5 = QtWidgets.QPushButton(Form)
        self.pbn_5.setGeometry(QtCore.QRect(360, 80, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_5.setFont(font)
        self.pbn_5.setText("")
        self.pbn_5.setDefault(False)
        self.pbn_5.setFlat(False)
        self.pbn_5.setObjectName("pbn_5")
        self.buttonGroup.addButton(self.pbn_5)
        self.pbn_6 = QtWidgets.QPushButton(Form)
        self.pbn_6.setGeometry(QtCore.QRect(200, 160, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_6.setFont(font)
        self.pbn_6.setText("")
        self.pbn_6.setDefault(False)
        self.pbn_6.setFlat(False)
        self.pbn_6.setObjectName("pbn_6")
        self.buttonGroup.addButton(self.pbn_6)
        self.pbn_7 = QtWidgets.QPushButton(Form)
        self.pbn_7.setGeometry(QtCore.QRect(40, 160, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_7.setFont(font)
        self.pbn_7.setText("")
        self.pbn_7.setDefault(False)
        self.pbn_7.setFlat(False)
        self.pbn_7.setObjectName("pbn_7")
        self.buttonGroup.addButton(self.pbn_7)
        self.pbn_8 = QtWidgets.QPushButton(Form)
        self.pbn_8.setGeometry(QtCore.QRect(120, 160, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_8.setFont(font)
        self.pbn_8.setText("")
        self.pbn_8.setDefault(False)
        self.pbn_8.setFlat(False)
        self.pbn_8.setObjectName("pbn_8")
        self.buttonGroup.addButton(self.pbn_8)
        self.pbn_9 = QtWidgets.QPushButton(Form)
        self.pbn_9.setGeometry(QtCore.QRect(280, 160, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_9.setFont(font)
        self.pbn_9.setText("")
        self.pbn_9.setDefault(False)
        self.pbn_9.setFlat(False)
        self.pbn_9.setObjectName("pbn_9")
        self.buttonGroup.addButton(self.pbn_9)
        self.pbn_10 = QtWidgets.QPushButton(Form)
        self.pbn_10.setGeometry(QtCore.QRect(360, 160, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_10.setFont(font)
        self.pbn_10.setText("")
        self.pbn_10.setDefault(False)
        self.pbn_10.setFlat(False)
        self.pbn_10.setObjectName("pbn_10")
        self.buttonGroup.addButton(self.pbn_10)
        self.pbn_11 = QtWidgets.QPushButton(Form)
        self.pbn_11.setGeometry(QtCore.QRect(200, 240, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_11.setFont(font)
        self.pbn_11.setText("")
        self.pbn_11.setDefault(False)
        self.pbn_11.setFlat(False)
        self.pbn_11.setObjectName("pbn_11")
        self.buttonGroup.addButton(self.pbn_11)
        self.pbn_12 = QtWidgets.QPushButton(Form)
        self.pbn_12.setGeometry(QtCore.QRect(40, 240, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_12.setFont(font)
        self.pbn_12.setText("")
        self.pbn_12.setDefault(False)
        self.pbn_12.setFlat(False)
        self.pbn_12.setObjectName("pbn_12")
        self.buttonGroup.addButton(self.pbn_12)
        self.pbn_13 = QtWidgets.QPushButton(Form)
        self.pbn_13.setGeometry(QtCore.QRect(120, 240, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_13.setFont(font)
        self.pbn_13.setText("")
        self.pbn_13.setDefault(False)
        self.pbn_13.setFlat(False)
        self.pbn_13.setObjectName("pbn_13")
        self.buttonGroup.addButton(self.pbn_13)
        self.pbn_14 = QtWidgets.QPushButton(Form)
        self.pbn_14.setGeometry(QtCore.QRect(280, 240, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_14.setFont(font)
        self.pbn_14.setText("")
        self.pbn_14.setDefault(False)
        self.pbn_14.setFlat(False)
        self.pbn_14.setObjectName("pbn_14")
        self.buttonGroup.addButton(self.pbn_14)
        self.pbn_15 = QtWidgets.QPushButton(Form)
        self.pbn_15.setGeometry(QtCore.QRect(360, 240, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_15.setFont(font)
        self.pbn_15.setText("")
        self.pbn_15.setDefault(False)
        self.pbn_15.setFlat(False)
        self.pbn_15.setObjectName("pbn_15")
        self.buttonGroup.addButton(self.pbn_15)
        self.pbn_16 = QtWidgets.QPushButton(Form)
        self.pbn_16.setGeometry(QtCore.QRect(200, 320, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_16.setFont(font)
        self.pbn_16.setText("")
        self.pbn_16.setDefault(False)
        self.pbn_16.setFlat(False)
        self.pbn_16.setObjectName("pbn_16")
        self.buttonGroup.addButton(self.pbn_16)
        self.pbn_17 = QtWidgets.QPushButton(Form)
        self.pbn_17.setGeometry(QtCore.QRect(40, 320, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_17.setFont(font)
        self.pbn_17.setText("")
        self.pbn_17.setDefault(False)
        self.pbn_17.setFlat(False)
        self.pbn_17.setObjectName("pbn_17")
        self.buttonGroup.addButton(self.pbn_17)
        self.pbn_18 = QtWidgets.QPushButton(Form)
        self.pbn_18.setGeometry(QtCore.QRect(120, 320, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_18.setFont(font)
        self.pbn_18.setText("")
        self.pbn_18.setDefault(False)
        self.pbn_18.setFlat(False)
        self.pbn_18.setObjectName("pbn_18")
        self.buttonGroup.addButton(self.pbn_18)
        self.pbn_19 = QtWidgets.QPushButton(Form)
        self.pbn_19.setGeometry(QtCore.QRect(280, 320, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_19.setFont(font)
        self.pbn_19.setText("")
        self.pbn_19.setDefault(False)
        self.pbn_19.setFlat(False)
        self.pbn_19.setObjectName("pbn_19")
        self.buttonGroup.addButton(self.pbn_19)
        self.pbn_20 = QtWidgets.QPushButton(Form)
        self.pbn_20.setGeometry(QtCore.QRect(360, 320, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_20.setFont(font)
        self.pbn_20.setText("")
        self.pbn_20.setDefault(False)
        self.pbn_20.setFlat(False)
        self.pbn_20.setObjectName("pbn_20")
        self.buttonGroup.addButton(self.pbn_20)
        self.pbn_21 = QtWidgets.QPushButton(Form)
        self.pbn_21.setGeometry(QtCore.QRect(200, 400, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_21.setFont(font)
        self.pbn_21.setText("")
        self.pbn_21.setDefault(False)
        self.pbn_21.setFlat(False)
        self.pbn_21.setObjectName("pbn_21")
        self.buttonGroup.addButton(self.pbn_21)
        self.pbn_22 = QtWidgets.QPushButton(Form)
        self.pbn_22.setGeometry(QtCore.QRect(40, 400, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_22.setFont(font)
        self.pbn_22.setText("")
        self.pbn_22.setDefault(False)
        self.pbn_22.setFlat(False)
        self.pbn_22.setObjectName("pbn_22")
        self.buttonGroup.addButton(self.pbn_22)
        self.pbn_23 = QtWidgets.QPushButton(Form)
        self.pbn_23.setGeometry(QtCore.QRect(120, 400, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_23.setFont(font)
        self.pbn_23.setText("")
        self.pbn_23.setDefault(False)
        self.pbn_23.setFlat(False)
        self.pbn_23.setObjectName("pbn_23")
        self.buttonGroup.addButton(self.pbn_23)
        self.pbn_24 = QtWidgets.QPushButton(Form)
        self.pbn_24.setGeometry(QtCore.QRect(280, 400, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_24.setFont(font)
        self.pbn_24.setText("")
        self.pbn_24.setDefault(False)
        self.pbn_24.setFlat(False)
        self.pbn_24.setObjectName("pbn_24")
        self.buttonGroup.addButton(self.pbn_24)
        self.pbn_25 = QtWidgets.QPushButton(Form)
        self.pbn_25.setGeometry(QtCore.QRect(360, 400, 75, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pbn_25.setFont(font)
        self.pbn_25.setText("")
        self.pbn_25.setDefault(False)
        self.pbn_25.setFlat(False)
        self.pbn_25.setObjectName("pbn_25")
        self.buttonGroup.addButton(self.pbn_25)
        self.label_time = QtWidgets.QLabel(Form)
        self.label_time.setGeometry(QtCore.QRect(70, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.label_press = QtWidgets.QLabel(Form)
        self.label_press.setGeometry(QtCore.QRect(280, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_press.setFont(font)
        self.label_press.setObjectName("label_press")
        self.pbn = QtWidgets.QPushButton(Form)
        self.pbn.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.pbn.setObjectName("pbn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_time.setText(_translate("Form", "Время: 0 с"))
        self.label_press.setText(_translate("Form", "Нажмите на кнопку"))
        self.pbn.setText(_translate("Form", "Начать"))
